definitions:
  lead.CreateLeadResponse:
    properties:
      lead:
        $ref: '#/definitions/lead.DisplayLead'
      message:
        type: string
      success:
        type: boolean
    type: object
  lead.DisplayLead:
    properties:
      company:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      phone:
        type: string
      updated_at:
        type: string
    type: object
  lead.InputLead:
    properties:
      company:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/lead:
    get:
      consumes:
      - application/json
      description: Get all leads
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/lead.DisplayLead'
            type: array
      summary: Get leads
      tags:
      - leads
    post:
      consumes:
      - application/json
      description: Create a new lead
      parameters:
      - description: New Lead
        in: body
        name: lead
        required: true
        schema:
          $ref: '#/definitions/lead.InputLead'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/lead.CreateLeadResponse'
      summary: Create a new lead
      tags:
      - leads
  /api/v1/lead/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a lead by ID
      parameters:
      - description: Lead ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lead.CreateLeadResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/lead.CreateLeadResponse'
      summary: Delete a lead
      tags:
      - leads
    get:
      consumes:
      - application/json
      description: Get a lead by ID
      parameters:
      - description: Lead ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/lead.DisplayLead'
      summary: Get a lead
      tags:
      - leads
swagger: "2.0"
